export const CATALOG_PAGES = {
  allProducts: {
    slug: "/tum-urunler",
    titleKey: "catalog.allProducts",
    titleTR: "Tüm Ürünler",
    titleEN: "All Products",
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: null,
    allowedSubcategories: null,
  },
  readyProducts: {
    slug: "/hazir-urunler",
    titleKey: "catalog.readyProducts",
    titleTR: "Hazır Ürünler",
    titleEN: "Ready Products",
    initialMainCategory: "C",
    initialSubcategory: "",
    allowedMainCategories: ["C"],
    allowedSubcategories: null,
  },
  artificialDry: {
    slug: "/cicek-cesitleri",
    titleKey: "catalog.artificialDry",
    titleTR: "Yapay ve Kuru Çiçekler",
    titleEN: "Artificial and Dried Flowers",
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: ["A", "B"],
    allowedSubcategories: null,
  },
  packaging: {
    slug: "/toptan-cicek-malzemesi-ambalaj-cesitleri",
    titleKey: "catalog.packaging",
    titleTR: "Ambalaj Çeşitleri",
    titleEN: "Packaging Types",
    initialMainCategory: "F",
    initialSubcategory: "",
    allowedMainCategories: ["F"],
    allowedSubcategories: null,
  },
  oasis: {
    slug: "/toptan-cicek-malzemesi-oasis-cesitleri",
    titleKey: "catalog.oasis",
    titleTR: "Oasis Çeşitleri",
    titleEN: "Oasis Types",
    initialMainCategory: "E",
    initialSubcategory: "E1",
    allowedMainCategories: ["E"],
    allowedSubcategories: ["E1"],
  },
};

export const CATALOG_PAGE_LIST = Object.values(CATALOG_PAGES);
