// Mock Data - Firebase entegrasyonu yapılana kadar kullanılacak

export const MOCK_CATEGORIES = [
  {
    id: "cat-1",
    slug: "yapay-cicek",
    nameTR: "Yapay Çiçek",
    nameEN: "Artificial Flowers",
    descriptionTR: "Kaliteli yapay çiçek çeşitleri",
    descriptionEN: "Quality artificial flowers",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 1,
  },
  {
    id: "cat-2",
    slug: "yapay-bitki",
    nameTR: "Yapay Bitki",
    nameEN: "Artificial Plants",
    descriptionTR: "Dekoratif yapay bitkiler",
    descriptionEN: "Decorative artificial plants",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 2,
  },
  {
    id: "cat-3",
    slug: "ambalaj",
    nameTR: "Ambalaj & Sunum",
    nameEN: "Packaging & Presentation",
    descriptionTR: "Çiçek ambalaj malzemeleri",
    descriptionEN: "Flower packaging materials",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 3,
  },
  {
    id: "cat-4",
    slug: "oasis",
    nameTR: "Oasis Çeşitleri",
    nameEN: "Oasis Types",
    descriptionTR: "Profesyonel oasis ürünleri",
    descriptionEN: "Professional oasis products",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 4,
  },
  {
    id: "cat-5",
    slug: "hazir-urunler",
    nameTR: "Hazır Ürünler",
    nameEN: "Ready Products",
    descriptionTR: "Hazır buket ve aranjmanlar",
    descriptionEN: "Ready bouquets and arrangements",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 5,
  },
  {
    id: "cat-6",
    slug: "kurdele",
    nameTR: "Kurdele Çeşitleri",
    nameEN: "Ribbon Types",
    descriptionTR: "Çiçek kurdeleleri",
    descriptionEN: "Flower ribbons",
    imageUrl: "/placeholder-category.jpg",
    isActive: true,
    deletedAt: null,
    sortOrder: 6,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "prod-1",
    slug: "kirmizi-gul-demeti",
    sku: "YC-001",
    nameTR: "Kırmızı Gül Demeti",
    nameEN: "Red Rose Bouquet",
    descriptionTR: "12 adet premium yapay kırmızı gül",
    descriptionEN: "12 pieces premium artificial red roses",
    priceRetail: 299,
    priceWholesale: 199,
    priceVip: 149,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: true,
    stock: 50,
    categoryId: "cat-1",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["gül", "kırmızı", "romantik"],
  },
  {
    id: "prod-2",
    slug: "beyaz-orkide",
    sku: "YC-002",
    nameTR: "Beyaz Orkide",
    nameEN: "White Orchid",
    descriptionTR: "Tek dallı yapay beyaz orkide",
    descriptionEN: "Single stem artificial white orchid",
    priceRetail: 449,
    priceWholesale: 349,
    priceVip: 299,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: true,
    stock: 30,
    categoryId: "cat-1",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["orkide", "beyaz", "elegant"],
  },
  {
    id: "prod-3",
    slug: "monstera-yapay",
    sku: "YB-001",
    nameTR: "Monstera Yapay Bitki",
    nameEN: "Artificial Monstera Plant",
    descriptionTR: "Büyük yapraklı dekoratif monstera",
    descriptionEN: "Large leaf decorative monstera",
    priceRetail: 599,
    priceWholesale: 449,
    priceVip: 399,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: true,
    stock: 25,
    categoryId: "cat-2",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["monstera", "yeşil", "tropikal"],
  },
  {
    id: "prod-4",
    slug: "kraft-ambalaj-kagidi",
    sku: "AM-001",
    nameTR: "Kraft Ambalaj Kağıdı",
    nameEN: "Kraft Wrapping Paper",
    descriptionTR: "50x70cm kraft ambalaj kağıdı - 50 adet",
    descriptionEN: "50x70cm kraft wrapping paper - 50 pieces",
    priceRetail: 199,
    priceWholesale: 149,
    priceVip: 99,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: false,
    stock: 100,
    categoryId: "cat-3",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["kraft", "ambalaj", "kağıt"],
  },
  {
    id: "prod-5",
    slug: "oasis-blok",
    sku: "OA-001",
    nameTR: "Oasis Blok",
    nameEN: "Oasis Block",
    descriptionTR: "Standart oasis blok - 10 adet",
    descriptionEN: "Standard oasis block - 10 pieces",
    priceRetail: 349,
    priceWholesale: 249,
    priceVip: 199,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: false,
    stock: 80,
    categoryId: "cat-4",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["oasis", "köpük", "aranjman"],
  },
  {
    id: "prod-6",
    slug: "hazir-gelin-buketi",
    sku: "HZ-001",
    nameTR: "Hazır Gelin Buketi",
    nameEN: "Ready Bridal Bouquet",
    descriptionTR: "Beyaz güller ve yeşilliklerle hazır gelin buketi",
    descriptionEN: "Ready bridal bouquet with white roses and greenery",
    priceRetail: 899,
    priceWholesale: 699,
    priceVip: 599,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: true,
    stock: 15,
    categoryId: "cat-5",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["gelin", "düğün", "buket"],
  },
  {
    id: "prod-7",
    slug: "saten-kurdele-kirmizi",
    sku: "KR-001",
    nameTR: "Saten Kurdele - Kırmızı",
    nameEN: "Satin Ribbon - Red",
    descriptionTR: "25mm genişlik, 25m rulo saten kurdele",
    descriptionEN: "25mm width, 25m roll satin ribbon",
    priceRetail: 79,
    priceWholesale: 59,
    priceVip: 49,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: false,
    stock: 200,
    categoryId: "cat-6",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["kurdele", "saten", "kırmızı"],
  },
  {
    id: "prod-8",
    slug: "pembe-lale-demeti",
    sku: "YC-003",
    nameTR: "Pembe Lale Demeti",
    nameEN: "Pink Tulip Bouquet",
    descriptionTR: "10 adet yapay pembe lale",
    descriptionEN: "10 pieces artificial pink tulips",
    priceRetail: 249,
    priceWholesale: 179,
    priceVip: 139,
    status: "PUBLISHED",
    isActive: true,
    isFeatured: true,
    stock: 40,
    categoryId: "cat-1",
    imageUrl: "/placeholder-product.png",
    images: ["/placeholder-product.png"],
    tags: ["lale", "pembe", "bahar"],
  },
];

export const MOCK_SETTINGS = {
  brand: {
    siteName: "Maxoy",
    tagline: "Toptan ve perakende yapay çiçek, dekor ve ambalaj",
    supportEmail: "destek@maxoy.com",
    supportPhone: "+90 850 000 00 00",
    whatsappPhone: "905XXXXXXXXX",
    address: "İstanbul, Türkiye",
    logoAssetId: null,
  },
  social: {
    instagram: "https://instagram.com/maxoy",
    facebook: "https://facebook.com/maxoy",
    twitter: null,
    tiktok: null,
  },
  shipping: {
    freeThreshold: 3000,
    baseFee: 149,
    expressMultiplier: 1.5,
  },
  checkout: {
    minOrderAmount: 100,
    maxOrderAmount: 100000,
    allowGuestCheckout: true,
  },
};

export const MOCK_HOMEPAGE = {
  status: "PUBLISHED",
  announcements: [
    {
      id: "ann-1",
      messageTR: "🎉 3000₺ üzeri siparişlerde ücretsiz kargo!",
      messageEN: "🎉 Free shipping on orders over 3000₺!",
      isActive: true,
      sortOrder: 0,
    },
  ],
  heroSlides: [
    {
      id: "hero-1",
      titleTR: "Yapay Çiçek & Bitki Dünyası",
      titleEN: "Artificial Flowers & Plants World",
      subtitleTR: "Profesyonellerin tercihi, en kaliteli ürünler",
      subtitleEN: "The choice of professionals, highest quality products",
      imageAssetId: "hero-1",
      ctaLink: "/tum-urunler",
      ctaTextTR: "Ürünleri Keşfet",
      ctaTextEN: "Explore Products",
      isActive: true,
      sortOrder: 0,
    },
  ],
  categoryCards: MOCK_CATEGORIES.slice(0, 4).map((cat, i) => {
    const slug = String(cat.slug || "").toLowerCase();
    const linkBySlug: Record<string, string> = {
      "yapay-cicek": "/cicek-cesitleri",
      "yapay-bitki": "/tum-urunler?category=A",
      ambalaj: "/toptan-cicek-malzemesi-ambalaj-cesitleri",
      oasis: "/toptan-cicek-malzemesi-oasis-cesitleri",
      "hazir-urunler": "/hazir-urunler",
      kurdele: "/kurdele-cesitleri",
    };

    return {
      id: `card-${i}`,
      titleTR: cat.nameTR,
      titleEN: cat.nameEN,
      descriptionTR: cat.descriptionTR,
      descriptionEN: cat.descriptionEN,
      imageAssetId: `cat-${i}`,
      link: linkBySlug[slug] || "/tum-urunler",
      sortOrder: i,
    };
  }),
  featured: MOCK_PRODUCTS.filter((p) => p.isFeatured).map((p, i) => ({
    id: `feat-${i}`,
    productId: p.id,
    product: p,
    sortOrder: i,
  })),
  trustBadges: [
    {
      id: "trust-1",
      icon: "🔒",
      textTR: "256 Bit SSL Güvenlik",
      textEN: "256 Bit SSL Security",
      sortOrder: 0,
    },
    {
      id: "trust-2",
      icon: "🚚",
      textTR: "Hızlı Kargo",
      textEN: "Fast Shipping",
      sortOrder: 1,
    },
    {
      id: "trust-3",
      icon: "💰",
      textTR: "Toptan Fiyat Avantajı",
      textEN: "Wholesale Price Advantage",
      sortOrder: 2,
    },
    {
      id: "trust-4",
      icon: "📞",
      textTR: "7/24 Destek",
      textEN: "24/7 Support",
      sortOrder: 3,
    },
  ],
};

export const MOCK_CATALOG_PAGES = [
  {
    key: "ALL_PRODUCTS",
    path: "/tum-urunler",
    titleTR: "Tüm Ürünler",
    titleEN: "All Products",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 0,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: true,
  },
  {
    key: "READY_PRODUCTS",
    path: "/hazir-urunler",
    titleTR: "Hazır Ürünler",
    titleEN: "Ready Products",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 1,
    initialMainCategory: "C",
    initialSubcategory: "",
    allowedMainCategories: ["C"],
    allowedSubcategories: [],
    navVisible: true,
  },
  {
    key: "ARTIFICIAL_DRY",
    path: "/cicek-cesitleri",
    titleTR: "Yapay ve Kuru Çiçekler",
    titleEN: "Artificial & Dried Flowers",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 2,
    initialMainCategory: "All",
    initialSubcategory: "",
    // Leave empty by default (admin can narrow down)
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: true,
  },
  {
    key: "PACKAGING",
    path: "/toptan-cicek-malzemesi-ambalaj-cesitleri",
    titleTR: "Ambalaj Çeşitleri",
    titleEN: "Packaging Types",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 3,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: true,
  },
  {
    key: "OASIS",
    path: "/toptan-cicek-malzemesi-oasis-cesitleri",
    titleTR: "Oasis Çeşitleri",
    titleEN: "Oasis Types",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 4,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: true,
  },
  {
    key: "RIBBONS",
    path: "/kurdele-cesitleri",
    titleTR: "Kurdele Çeşitleri",
    titleEN: "Ribbon Types",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 5,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: false,
  },
  {
    key: "BOXES",
    path: "/kutu-cesitleri",
    titleTR: "Kutu Çeşitleri",
    titleEN: "Box Types",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 6,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: false,
  },
  {
    key: "SUPPLIES",
    path: "/toptan-cicek-malzemesi-tuhafiye-malzemeleri",
    titleTR: "Malzeme Çeşitleri",
    titleEN: "Supplies",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 7,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: false,
  },
  {
    key: "CERAMIC_BAGS",
    path: "/seramik-cantalar",
    titleTR: "Seramik & Çantalar",
    titleEN: "Ceramics & Bags",
    status: "PUBLISHED",
    publishedAt: new Date().toISOString(),
    sortOrder: 8,
    initialMainCategory: "All",
    initialSubcategory: "",
    allowedMainCategories: [],
    allowedSubcategories: [],
    navVisible: false,
  },
];

// ---------------------------------------------------------------------------
// Compatibility exports (used by lib/db.ts mock Prisma client)
// ---------------------------------------------------------------------------

export const mockCategories = MOCK_CATEGORIES;
export const mockProducts = MOCK_PRODUCTS;

// Admin Settings model shape: { id, data }
export const mockSettings = {
  id: "settings-1",
  data: {
    brand: {
      siteName: MOCK_SETTINGS.brand.siteName,
      logoAssetId: MOCK_SETTINGS.brand.logoAssetId ?? null,
      faviconAssetId: null,
    },
    contact: {
      phone: MOCK_SETTINGS.brand.supportPhone || "",
      whatsapp: MOCK_SETTINGS.brand.whatsappPhone || "",
      email: MOCK_SETTINGS.brand.supportEmail || "",
      address: MOCK_SETTINGS.brand.address || "",
    },
    shipping: {
      freeShippingThreshold: MOCK_SETTINGS.shipping.freeThreshold,
      estimatedDaysTextTR: "",
      estimatedDaysTextEN: "",
    },
    social: {
      instagram: MOCK_SETTINGS.social.instagram || "",
      facebook: MOCK_SETTINGS.social.facebook || "",
      tiktok: MOCK_SETTINGS.social.tiktok || "",
    },
    legal: {
      companyName: "",
      taxOffice: "",
      taxNo: "",
    },
  },
};

export const mockHomePage = {
  id: "home-1",
  status: MOCK_HOMEPAGE.status,
  publishedAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  announcements: MOCK_HOMEPAGE.announcements,
  heroSlides: MOCK_HOMEPAGE.heroSlides,
  categoryCards: MOCK_HOMEPAGE.categoryCards,
  featured: MOCK_HOMEPAGE.featured,
  trustBadges: MOCK_HOMEPAGE.trustBadges,
};

export const mockCatalogPages = MOCK_CATALOG_PAGES.map((p, i) => ({
  id: `catpage-${i + 1}`,
  ...p,
}));

// Minimal MediaAsset-like map for admin preview + storefront images
export const mockMediaAssets: Record<
  string,
  {
    id: string;
    key: string;
    url: string;
    mime: string;
    size: number;
    width?: number | null;
    height?: number | null;
    altText: string;
    folder?: string | null;
    blurDataUrl?: string | null;
    variants?: any;
    createdAt: string;
    updatedAt: string;
    deletedAt?: string | null;
  }
> = {
  "hero-1": {
    id: "hero-1",
    key: "hero-1",
    url: "/hero-image.png",
    mime: "image/png",
    size: 0,
    width: 1600,
    height: 900,
    altText: "Hero",
    folder: "home",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  "cat-0": {
    id: "cat-0",
    key: "cat-0",
    url: "/placeholder-product.png",
    mime: "image/png",
    size: 0,
    width: 1200,
    height: 800,
    altText: "Category",
    folder: "home",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  "cat-1": {
    id: "cat-1",
    key: "cat-1",
    url: "/placeholder-product.png",
    mime: "image/png",
    size: 0,
    width: 1200,
    height: 800,
    altText: "Category",
    folder: "home",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  "cat-2": {
    id: "cat-2",
    key: "cat-2",
    url: "/placeholder-product.png",
    mime: "image/png",
    size: 0,
    width: 1200,
    height: 800,
    altText: "Category",
    folder: "home",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  "cat-3": {
    id: "cat-3",
    key: "cat-3",
    url: "/placeholder-product.png",
    mime: "image/png",
    size: 0,
    width: 1200,
    height: 800,
    altText: "Category",
    folder: "home",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};
